openapi: "3.0.0"
info:
  title: API для получения попапа с предложенным заданием
  version: "1.0.0"
paths:
  /v110/tasks/proposed-task:
    get:
      summary: Получить попап с предложенным заданием
      description: |
        Возвращает:
        - `title`: массив отформатированных блоков заголовка
        - `message`: массив отформатированных блоков основного текста
        - `plain_text`: fallback для старых клиентов
        - `task_link`: ссылка на задание
        - `icon`: ссылка на иконку
      responses:
        '200':
          description: Успешный ответ с данными сообщения
          content:
            application/json:
              schema:
                type: object
                properties:
                  icon:
                    type: string
                    format: uri
                    description: URL иконки
                  plain_text:
                    type: string
                    description: Объединённый fallback текст
                  task_link:
                    type: string
                    format: uri
                    description: Ссылка на задание
                  title:
                    type: array
                    description: Заголовок
                    items:
                      $ref: '#/components/schemas/FormattedText'
                  message:
                    type: array
                    description: Основной текст
                    items:
                      $ref: '#/components/schemas/FormattedText'
                required:
                  - icon
                  - plain_text
                  - task_link
                  - title
                  - message
              example:
                icon: "https://avatar.youdo.com/get.userAvatar?AvatarId=0\u0026AvatarType=H60W60"
                plain_text: "Вам предложили задание «Привезти мягкую игрушку»\nОткликнетесь на предложенное задание"
                task_link: "https://youdo.com/t13619539"
                title:
                  - text: "Вам предложили задание "
                    style: "bold"
                  - text: "«Привезти мягкую игрушку»"
                    style: "bold_blue"
                message:
                  - text: "\nОткликнетесь на предложенное задание"
                    style: "regular"


        '400':
          description: Неверный запрос (например, отсутствует обязательное поле)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponse'

        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

components:
  schemas:
    FormattedText:
      type: object
      properties:
        text:
          type: string
          description: Текстовая часть сообщения
          example: "Вам предложили задание "
        style:
          type: string
          description: Стиль форматирования
          example: "bold"
          enum:
            - bold
            - bold_blue
            - regular
      required:
        - text
        - style

    ClientErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              example: 400
            message:
              type: string
              example: "Invalid request"
            details:
              type: string
              example: "Field 'email' is required"
            requestId:
              type: string
              example: "xyz456pqr"
            timestamp:
              type: string
              format: date-time
              example: "2025-04-14T22:34:56Z"
          required:
            - code
            - message
            - details
            - requestId
            - timestamp

    ServerErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              example: 500
            message:
              type: string
              example: "Internal server error"
            requestId:
              type: string
              example: "abc123xyz"
            timestamp:
              type: string
              format: date-time
              example: "2025-04-14T22:34:56Z"
          required:
            - code
            - message
            - requestId
            - timestamp
